# Stalker Coordination Environment Configuration

env: "sc2_stalker_coordination"
env_args:
  map_name: "3s5z_vs_3s6z"  
  seed: 42
  coordination_reward: 0.2  
  stalker_role_id: 0  # Role ID for Stalkers

  difficulty: "7"  
  reward_only_positive: True  
  reward_death_value: 10  
  reward_win: 200 
  reward_defeat: 0  

common_reward: True
reward_scalarisation: "sum"
